---
- name: MySQL database
  hosts: dbserver
  tasks:
    - name: Install MySQL
      ansible.builtin.dnf:
        name:
          - mysql-server
          - mysql
          - python3-pymysql
        state: latest
      become: true

    - name: Start MySQL service
      ansible.builtin.service:
         name: mysqld
         state: started
         enabled: yes
      become: true

    - name: Creating MySQL user
      community.mysql.mysql_user:
        name: "dbuser"
        password: "dbpass"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create MySQL database
      community.mysql.mysql_db:
        name: db1
        state: present

