---
- name: Backup/Restore MySQL database
  hosts: dbserver
  vars_files:
    - vars.yml
  tasks:

    - name: Dump MySQL databases
      community.mysql.mysql_db:
        name: "{{ databases }}"
        state: dump
        #target: all
        target: "{{ dump_file }}"

    - name: Delete MySQL databases
      community.mysql.mysql_db:
        name: "{{ databases }}"
        state: absent

    - name: Create MySQL databases
      community.mysql.mysql_db:
        name: "{{ databases }}"
        state: present

    - name: Import MySQL databases
      community.mysql.mysql_db:
        name: "{{ databases }}"
        state: import
        #target: all
        target: "{{ dump_file }}"

    - name: Select MySQL tables
      community.mysql.mysql_query:
        login_db: "{{ sql.dbname }}"
        query: "{{ item }}"
      loop: "{{ sql.select }}"
