---
- name: MySQL database
  hosts: dbserver
  tasks:
    - name: Install MySQL
      ansible.builtin.dnf:
         name: 
            - mysql-server
            - mysql-client 
            - python3-mysqldb
            - libmysqlclient-dev
         state: latest

    - name: Start MySQL
      ansible.builtin.service:
         name: mysql
         state: started
         enabled: yes

    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: db1
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create new databases
      community.mysql.mysql_db:
        name:
          - db1
          - db2
        state: present