---
- name: Backup/Restore MySQL database
  hosts: dbserver
  vars_files:
    - vars.yml
  tasks:

    - name: Dump MySQL databases
      community.mysql.mysql_db:
        name: "{{ databases }}"
        state: dump
        #target: all
        target: "{{ dump_file }}"

    - name: Import MySQL databases
      community.mysql.mysql_db:
        name: "{{ databases }}"
        state: import
        #target: all
        target: "{{ dump_file }}"
