---
- name: MySQL database
  hosts: dbserver
  tasks:
    - name: Install MySQL
      ansible.builtin.yum:
        name:
          - mariadb
          #- mysql-server
          # - mysql-client 
          # - python3-mysqldb
          # - libmysqlclient-dev
        state: latest
      become: true

    - name: Start MySQL service
      ansible.builtin.service:
         name: mariadb
         #state: started
         enabled: yes
      become: true

    - name: Create a new database
      community.mysql.mysql_db:
        name: db1
        state: present