---
- name: Replication MySQL database
  hosts: dbserver
  vars_files:
    - vars.yml
  tasks:
    
    - name: Create MySQL tables
      community.mysql.mysql_query:
        query: "{{ item.sql }}"
      loop: "{{ sql.create }}"

    - name: Insert MySQL tables
      community.mysql.mysql_query:
        query: "{{ item.sql }}"
        positional_args: "{{ item.values }}"
        single_transaction: true
      loop: "{{ sql.insert }}"

    - name: Select MySQL tables
      community.mysql.mysql_query:
        query: "{{ item.sql }}"
      loop: "{{ sql.create }}"
