---
- name: Replication MySQL database
  hosts: dbserver
  vars_files:
    - vars.yml
  tasks:

    - name: Get primary binlog file name and binlog position
      community.mysql.mysql_replication:
        mode: getprimary

    - name: Check Replication MySQL databases
      community.mysql.mysql_replication:
        mode: getreplica
        login_host: "{{ ansible_host }}"
        login_port: 3308

    - name: Change Primary MySQL databases
      community.mysql.mysql_replication:
        mode: changeprimary
        primary_host: "{{ ansible_host }}"
