---
- name: MySQL database
  hosts: dbserver
  tasks:
    - name: Install MySQL
      ansible.builtin.dnf:
        name:
          - mysql-server
          - mysql
        state: latest
      become: true

    - name: Start MySQL service
      ansible.builtin.service:
         name: mysqld
         #state: started
         enabled: yes
      become: true

    - name: Create a new database
      community.mysql.mysql_db:
        name: db1
        state: present

