---
- name: Replication MySQL database
  hosts: dbserver
  vars_files:
    - vars.yml
  tasks:

    - name: Get Primary MySQL databases
      community.mysql.mysql_replication:
        mode: getprimary

    # - name: Start MariaDB replica with connection name primary-1
    #   community.mysql.mysql_replication:
    #     mode: startreplica
    #     connection_name: primary-1

    - name: Check Replication MySQL databases
      community.mysql.mysql_replication:
        mode: getreplica
        # login_host: "{{ ansible_host }}"
        # login_port: 3306

    - name: Change Primary MySQL databases
      community.mysql.mysql_replication:
        mode: changeprimary
        primary_host: "{{ ansible_host }}"
