---
- name: Replication MySQL database
  hosts: dbserver
  vars_files:
    - vars.yml
  tasks:

    - name: Get Primary MySQL databases
      community.mysql.mysql_replication:
        mode: getprimary

    - name: Check Replication MySQL databases
      community.mysql.mysql_replication:
        mode: getreplica

    - name: Change Primary MySQL databases
      community.mysql.mysql_replication:
        mode: changeprimary
        primary_host: "{{ ansible_host }}"
