---
- name: MySQL database
  hosts: dbserver
  tasks:
    - name: Install MySQL
      ansible.builtin.dnf:
         name: mysql
         state: latest

    - name: Start MySQL
      ansible.builtin.service:
         name: mysql
         enabled: yes

    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: db1
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create new databases with names 'foo' and 'bar'
      community.mysql.mysql_db:
        name:
          - db1
          - db2
        state: present