---
- name: MySQL database
  hosts: dbserver
  tasks:
    - name: Install MySQL
      ansible.builtin.yum:
         name: 
            - mysql-server
            # - mysql-client 
            # - python3-mysqldb
            # - libmysqlclient-dev
         state: latest

    - name: Start MySQL service
      ansible.builtin.service:
         name: mysql
         state: started
         enabled: yes

    - name: Create a new database
      community.mysql.mysql_db:
        name: db1
        state: present